### PR TITLE
First version of the admin page

### PR DESCRIPTION
**Pull request by kevin33c**
Screenshot 2022-11-01 at 23 56 46

First version of the admin page with stepper:
1. create session
2. add emails of participants
3. send invitations
4. scramble

### CODE REVIEW

**Comment by kevin33c** [comment]
Note, this is probably not compatible to what Jeong did, so we probably need to discuss how to proceed from here.

**Comment by KadarTibor** [comment]
This looks very nice! Can the individual steps be navigated to via a url path?

**Review by KadarTibor — APPROVED** [review]

**Comment by kevin33c** [comment]
Yes sure, I'm not using it yet but basically there is an onInit function as well that I can call which then I can parse the url to get the ID for which individual step we want an user to land

**Review by overlakehome — APPROVED** [review]
It looks good. I will pull your commit and make a change on my PR

**Comment by overlakehome** [comment]
Sure. Please merge it.

**Pull request merged**
